# Generated by Django 4.0.4 on 2022-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluidbooking',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='fluidbooking',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
